#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# KK Connect — Fresh VM Setup Script
# Run this on a fresh GCE instance (Ubuntu 22.04+ / Debian 12+)
# =============================================================================

echo "==> Installing Docker..."
if ! command -v docker &>/dev/null; then
  curl -fsSL https://get.docker.com | sh
  sudo usermod -aG docker "$USER"
  echo "Docker installed. Log out and back in, then re-run this script."
  exit 0
fi

echo "==> Installing Docker Compose plugin..."
sudo apt-get update -qq
sudo apt-get install -y -qq docker-compose-plugin git

echo "==> Cloning repository..."
REPO_DIR="$HOME/kumuda-communication"
# Also check legacy path in case script was run before the rename
if [ -d "$REPO_DIR" ]; then
  echo "    Repo already exists at $REPO_DIR, pulling latest..."
  cd "$REPO_DIR" && git pull origin main
elif [ -d "$HOME/dograh" ]; then
  REPO_DIR="$HOME/dograh"
  echo "    Repo found at legacy path $REPO_DIR, pulling latest..."
  cd "$REPO_DIR" && git pull origin main
else
  git clone https://github.com/rushinandigam/kumuda-communication.git "$REPO_DIR"
  cd "$REPO_DIR"
fi

echo "==> Generating .env file with fresh credentials..."
cat > "$REPO_DIR/.env" << 'ENVEOF'
# === KK Connect Production Environment ===
# Generated by setup_vm.sh — rotate these if compromised.

ENVIRONMENT=production

# --- Secrets (auto-generated) ---
POSTGRES_PASSWORD=6185987d1ce92fc362c07d1ec1ef2d63417e710fe92a1d3b783f4e00d7dadd34
REDIS_PASSWORD=0278b70cc7a1ae86558e4f9a145e41ea3c476abb25c4280c0b8ead6e431792aa
OSS_JWT_SECRET=5257d9ab03ad8a8e99071db3f65ec458ab5539bf035cf21e54421f7fbfe8b7eb

# --- Public URL (update after VM gets a new IP) ---
PUBLIC_BASE_URL=https://YOUR-IP.sslip.io
PUBLIC_HOST=YOUR-IP.sslip.io

# --- GCS Storage ---
GCS_ACCESS_KEY_ID=REPLACE_WITH_GCS_HMAC_KEY
GCS_ACCESS_KEY_SECRET=REPLACE_WITH_GCS_HMAC_SECRET

# --- Workers ---
FASTAPI_WORKERS=2
ENVEOF

echo "==> Creating API .env..."
cat > "$REPO_DIR/api/.env" << 'APIENVEOF'
DATABASE_URL=postgresql+asyncpg://postgres:6185987d1ce92fc362c07d1ec1ef2d63417e710fe92a1d3b783f4e00d7dadd34@postgres:5432/postgres
REDIS_URL=redis://:0278b70cc7a1ae86558e4f9a145e41ea3c476abb25c4280c0b8ead6e431792aa@redis:6379
APIENVEOF

echo "==> Setting up GCP firewall rules..."
echo "    Run these commands from your LOCAL machine (not the VM):"
echo ""
echo "    # Delete overly permissive rules"
echo "    gcloud compute firewall-rules delete default-allow-all --project=kumuda-d2c11 --quiet 2>/dev/null || true"
echo ""
echo "    # Allow only HTTP/HTTPS + IAP SSH"
echo "    gcloud compute firewall-rules create allow-https-only \\"
echo "      --project=kumuda-d2c11 \\"
echo "      --direction=INGRESS \\"
echo "      --priority=1000 \\"
echo "      --network=default \\"
echo "      --action=ALLOW \\"
echo "      --rules=tcp:80,tcp:443 \\"
echo "      --source-ranges=0.0.0.0/0"
echo ""
echo "    gcloud compute firewall-rules create allow-iap-ssh \\"
echo "      --project=kumuda-d2c11 \\"
echo "      --direction=INGRESS \\"
echo "      --priority=1000 \\"
echo "      --network=default \\"
echo "      --action=ALLOW \\"
echo "      --rules=tcp:22 \\"
echo "      --source-ranges=35.235.240.0/20"
echo ""

echo "==> Building UI image from source..."
docker build -t kkconnect-ui:latest -f ui/Dockerfile .

echo "==> Pulling API image (requires pipecat submodule to build from source)..."
docker pull dograhai/dograh-api:latest

echo "==> Starting the stack..."
docker compose up -d

echo "==> Setting up Caddy for HTTPS..."
# Create a Caddy container for TLS termination
docker network create caddy-net 2>/dev/null || true
docker network connect caddy-net "$(docker compose ps -q api)" 2>/dev/null || true
docker network connect caddy-net "$(docker compose ps -q ui)" 2>/dev/null || true

echo ""
echo "============================================"
echo "  SETUP COMPLETE"
echo "============================================"
echo ""
echo "Next steps:"
echo "  1. Update .env with your actual GCS HMAC keys and the VM's public IP"
echo "  2. Run the firewall commands above from your local machine"
echo "  3. Set up Caddy with your domain (see below)"
echo "  4. Restart: docker compose down && docker compose up -d"
echo ""
echo "Caddy setup:"
echo "  docker run -d --name caddy --network caddy-net \\"
echo "    -p 80:80 -p 443:443 \\"
echo "    -v caddy_data:/data -v caddy_config:/config \\"
echo "    -v \$PWD/Caddyfile:/etc/caddy/Caddyfile \\"
echo "    caddy:2"
echo ""
